//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace halaStoer
{
    using System;
    using System.Collections.Generic;
    
    public partial class command
    {
        public int idCmd { get; set; }
        public string Nomclient { get; set; }
        public string NomProduit { get; set; }
        public int Qnt { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<System.DateTime> Date_Cmd { get; set; }
        public Nullable<int> id_F { get; set; }
    
        public virtual factur factur { get; set; }
    }
}
