//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace halaStoer
{
    using System;
    using System.Collections.Generic;
    
    public partial class factur
    {
        public factur()
        {
            this.commands = new HashSet<command>();
        }
    
        public int id_F { get; set; }
        public string Nomclient { get; set; }
        public string NomProduit { get; set; }
        public int Qnt { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual ICollection<command> commands { get; set; }
    }
}
